name: configuration

on:
  push:
    branches:
      - main

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: InvokeBuild:5.10.1, InvokeBuildHelper:3.1.0
      - name: Run PowerShell module Unit tests
        shell: pwsh
        run: |
          Write-Host $pwd
          $Global:VerbosePreference = 'Continue'
          Invoke-Build -Task 'UnitTest'
      - name: Run PowerShell module Schema tests
        shell: pwsh
        run: |
          Invoke-Build -Task 'SchemaTest'
      - name: Run PowerShell module Analyzer tests
        shell: pwsh
        run: |
          Invoke-Build -Task 'AnalyzerTest'
