name: CI

on:
  push:
    branches:
      - main

jobs:
  windows-powershell-legacy:
    name: Windows PowerShell 5.1
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          shell: powershell
          modules-to-cache: Pester:5.3.3, PSScriptAnalyzer:1.21.0, SecurityFever:2.8.1, InvokeBuild:5.10.1, InvokeBuildHelper:3.1.0
      - name: Run PowerShell module Schema tests
        shell: powershell
        run: |
          $Global:VerbosePreference = 'Continue'
          Invoke-Build -Task 'SchemaTest'
      - name: Run PowerShell module Unit tests
        shell: powershell
        run: |
          $Global:VerbosePreference = 'Continue'
          Invoke-Build -Task 'UnitTest'
      - name: Run PowerShell module Analyzer tests
        shell: powershell
        run: |
          $Global:VerbosePreference = 'Continue'
          Invoke-Build -Task 'AnalyzerTest'
