name: configuration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: InvokeBuild::5.10.1, InvokeBuildHelper:3.1.0, PSScriptAnalyzer:1.21.0
      - name: Test PowerShell module
        shell: pwsh
        run: |
          Invoke-Build -Task 'Test'
